### ISSUE TITLE
How to use gesture methods defined in  leap_interface.py to improve my sender.py script

### ISSUE THREAD

**Issue by stevensu1838** [ros-drivers/leap_motion#51]
Hi,
Merry Christmas.

I am using the sender.py script to read the hand_palm_pos_ data in order to control my robot. 
This line is used to launch the sender.py script `source ~/catkin_ws/devel/setup.bash && rosrun leap_motion sender.py ` and it works very well. 

And I am aware of that it is doable to use gestures to control something with LeapMotion sensor.  I've seen a commented part of code in the  leap_interface.py script as shown below:
```
 # Gestures
            for gesture in frame.gestures():
                if gesture.type == Leap.Gesture.TYPE_CIRCLE:
                    circle = CircleGesture(gesture)
                    # Determine clock direction using the angle between the pointable and the circle normal
                    if circle.pointable.direction.angle_to(circle.normal) <= Leap.PI/4:
                        clockwiseness = "clockwise"
                    else:
                        clockwiseness = "counterclockwise"
                    # Calculate the angle swept since the last frame
                    swept_angle = 0
                    if circle.state != Leap.Gesture.STATE_START:
                        previous_update = CircleGesture(controller.frame(1).gesture(circle.id))
                        swept_angle =  (circle.progress - previous_update.progress) * 2 * Leap.PI
                    print "Circle id: %d, %s, progress: %f, radius: %f, angle: %f degrees, %s" % (
                            gesture.id, self.state_string(gesture.state),
                            circle.progress, circle.radius, swept_angle * Leap.RAD_TO_DEG, clockwiseness)

```
I am a new programmer. Can you please tell me why this part is commented out? How can I use this part about gestures leap_interface.py script in to improve the sender.py script in order to not only send hand postions but also gestures to control my robot better? 
Thanks a million for all the help that you've given me.

BR,
Steven

**Comment by nowittyusername** [comment]
> Can you please tell me why this part is commented out? 

I have no idea why, probably because it doesn't work maybe? I had a quick glance at it and didn't really find anything that would indicate that it won't work but I didn't write that python code so I ain't sure. ¯\\_(ツ)_/¯

 > How can I use this part about gestures leap_interface.py script in to improve the sender.py script in order to not only send hand postions but also gestures to control my robot better?

The key parts are these lines https://github.com/ros-drivers/leap_motion/blob/46956212de550f8f227879ca00d94b82a0e61e1c/scripts/leap_interface.py#L98

https://github.com/ros-drivers/leap_motion/blob/46956212de550f8f227879ca00d94b82a0e61e1c/scripts/leap_interface.py#L164

You need to get a frame in sender.py like the line 98 in leap_interface and then you can pretty much copy paste the code from the leap_interface to sender.py.
